services:
  postgres-preprod:
    image: postgres:16.1-alpine
    profiles: ["preprod"]
    env_file: ./.env
    environment:
      - POSTGRES_LOGGING=true
    ports:
      - 127.0.0.1:5433:5432
    shm_size: '2gb'
    volumes:
      - ./config/postgresql/postgresql.testnet.conf:/etc/postgresql.conf
      - postgres-data-preprod:/var/lib/postgresql/data
    command: [
      "-c", "config_file=/etc/postgresql.conf"
    ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-node-ogmios-preprod:
    image: cardanosolutions/cardano-node-ogmios:v6.3.0_8.10.1-pre-preview
    profiles: ["preprod"]
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - 127.0.0.1:1338:1337
      - 3001:3000
    volumes:
      - node-db-preprod:/db
      - node-ipc-preprod:/ipc
    restart: on-failure

  cardano-db-sync-preprod:
#    image: ghcr.io/intersectmbo/cardano-db-sync:13.2.0.2
    build:
      context: .
      target: cardano-db-sync
    profiles: ["preprod"]
    env_file: ./.env
    command: [
      "--config", "config/cardano-db-sync/config.json",
      "--socket-path", "/node-ipc/node.socket",
      "--consumed-tx-out"
    ]
    environment:
      - EKG=Y
      - RESTORE_SNAPSHOT=${RESTORE_SNAPSHOT_PREPROD:-}
      - POSTGRES_HOST=postgres-preprod
      - POSTGRES_PORT=5432
    depends_on:
      - cardano-node-ogmios-preprod
      - postgres-preprod
    volumes:
      - ./config/cardano-configurations/network/preprod:/config
      - node-ipc-preprod:/node-ipc
      - db-sync-data-preprod:/var/lib/cexplorer
    restart: on-failure
    stop_signal: SIGINT
    logging:
      driver: "local"
      options:
        max-size: "200k"
        max-file: "10"

  koios-tiny-preprod:
    profiles: ["preprod"]
    build:
      context: .
      target: koios-tiny
    env_file: ./.env
    environment:
      - NETWORK=preprod
      - POSTGRES_HOST=postgres-preprod
      - POSTGRES_PORT=5432
      - PGHOST=postgres-preprod
      - PGPORT=5432
      - PGRST_DB_URI=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres-preprod:5432/$POSTGRES_DB
    ports:
      - 127.0.0.1:8051:8050
    depends_on:
      - postgres-preprod
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  db-sync-data-preprod:
  node-db-preprod:
  node-ipc-preprod:
  postgres-data-preprod:
