version: "3.8"

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-16.1-alpine}
    env_file: ./.env
    environment:
      - POSTGRES_LOGGING=true
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    shm_size: '2gb'
    volumes:
      - ./config/postgresql/postgresql.conf:/etc/postgresql.conf
      - postgres-data:/var/lib/postgresql/data
    command: [
      "-c", "config_file=/etc/postgresql.conf"
    ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-node-ogmios:
    image: cardanosolutions/cardano-node-ogmios:${OGMIOS_VERSION:-v6.0.0-rc5}_${CARDANO_NODE_VERSION:-8.1.2}-${NETWORK:-mainnet}
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - ${OGMIOS_PORT:-1337}:1337
      - ${CARDANO_NODE_PORT:-3000}:3000
    volumes:
      - node-db:/db
      - node-ipc:/ipc
    restart: on-failure


  cardano-db-sync:
    image: inputoutput/cardano-db-sync:${CARDANO_DB_SYNC_VERSION:-13.1.1.3}
    env_file: ./.env
    command: [
      "--config", "/config-db-sync/config.json",
      "--socket-path", "/node-ipc/node.socket",
      "--consumed-tx-out"
    ]
    environment:
      - EKG=Y
      - RESTORE_SNAPSHOT=${RESTORE_SNAPSHOT:-}
      - RESTORE_RECREATE_DB=N
    depends_on:
      - cardano-node-ogmios
      - postgres
    volumes:
      - ./config/cardano-db-sync/${NETWORK:-mainnet}:/config-db-sync
      - ./config/cardano-configurations/network/${NETWORK:-mainnet}:/config
      - node-ipc:/node-ipc
      - db-sync-data:/var/lib/cexplorer
      - db-sync-logs:/db-sync-logs
    restart: on-failure
    stop_signal: SIGINT
    logging:
      driver: "local"
      options:
        max-size: "200k"
        max-file: "10"

  koios-tiny:
    build:
      context: .
      target: koios-tiny
    env_file: ./.env
    environment:
      - NETWORK=${NETWORK:-mainnet}
    ports:
      - ${KOIOS_TINY_PORT:-8050}:8050
    depends_on:
      - postgres
    volumes:
      - db-sync-logs:/home/logs
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  db-sync-logs:
  db-sync-data:
  node-db:
  node-ipc:
  postgres-data:

