services:
  postgres-mainnet:
    image: postgres:16.1-alpine
    profiles: ["mainnet"]
    env_file: ./.env
    environment:
      - POSTGRES_LOGGING=true
    ports:
      - 127.0.0.1:5432:5432
    shm_size: '2gb'
    volumes:
      - ./config/postgresql/postgresql.conf:/etc/postgresql.conf
      - postgres-data-mainnet:/var/lib/postgresql/data
    command: [
      "-c", "config_file=/etc/postgresql.conf"
    ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-node-ogmios-mainnet:
    image: cardanosolutions/cardano-node-ogmios:v6.1.0_8.7.3-mainnet
    profiles: ["mainnet"]
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - 127.0.0.1:1337:1337
      - 3000:3000
    volumes:
      - node-db-mainnet:/db
      - node-ipc-mainnet:/ipc
    restart: on-failure

  cardano-db-sync-mainnet:
    image: ghcr.io/intersectmbo/cardano-db-sync:13.1.1.3
    profiles: ["mainnet"]
    env_file: ./.env
    command: [
      "--config", "/config-db-sync/config.json",
      "--socket-path", "/node-ipc/node.socket",
      "--consumed-tx-out"
    ]
    environment:
      - EKG=Y
      - RESTORE_SNAPSHOT=${RESTORE_SNAPSHOT_MAINNET:-}
      - RESTORE_RECREATE_DB=N
      - POSTGRES_HOST=postgres-mainnet
      - POSTGRES_PORT=5432
    depends_on:
      - cardano-node-ogmios-mainnet
      - postgres-mainnet
    volumes:
      - ./config/cardano-db-sync/mainnet:/config-db-sync
      - ./config/cardano-configurations/network/mainnet:/config
      - node-ipc-mainnet:/node-ipc
      - db-sync-data-mainnet:/var/lib/cexplorer
      - db-sync-logs-mainnet:/db-sync-logs
    restart: on-failure
    stop_signal: SIGINT
    logging:
      driver: "local"
      options:
        max-size: "200k"
        max-file: "10"

  koios-tiny-mainnet:
    profiles: ["mainnet"]
    build:
      context: .
      target: koios-tiny
    env_file: ./.env
    environment:
      - NETWORK=mainnet
      - POSTGRES_HOST=postgres-mainnet
      - POSTGRES_PORT=5432
      - PGHOST=postgres-preview
      - PGPORT=5432
      - PGRST_DB_URI=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres-preview:5432/$POSTGRES_DB
    ports:
      - 127.0.0.1:8050:8050
    depends_on:
      - postgres-mainnet
    volumes:
      - db-sync-logs-mainnet:/home/logs
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  db-sync-logs-mainnet:
  db-sync-data-mainnet:
  node-db-mainnet:
  node-ipc-mainnet:
  postgres-data-mainnet:
