name: koios-tiny

services:
  haproxy:
    image: haproxy:2.8.3
    profiles: ["mainnet", "preprod", "preview"]
    env_file: ./.env
    ports:
      - 80:8080
      - 443:8443
    shm_size: '2gb'
    volumes:
      - ./config/haproxy:/usr/local/etc/haproxy
      - /etc/ssl/ssl_key.pem:/ssl_key.pem
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

include:
  - docker-compose.mainnet.yml
  - docker-compose.preprod.yml
  - docker-compose.preview.yml
