services:
  postgres-preview:
    image: postgres:16.1-alpine
    profiles: ["preview"]
    env_file: ./.env
    environment:
      - POSTGRES_LOGGING=true
    ports:
      - 127.0.0.1:5434:5432
    shm_size: '2gb'
    volumes:
      - ./config/postgresql/postgresql.testnet.conf:/etc/postgresql.conf
      - postgres-data-preview:/var/lib/postgresql/data
    command: [
      "-c", "config_file=/etc/postgresql.conf"
    ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-node-ogmios-preview:
    image: cardanosolutions/cardano-node-ogmios:v6.3.0_8.10.1-pre-preview
    profiles: ["preview"]
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - 127.0.0.1:1339:1337
      - 3002:3000
    volumes:
      - node-db-preview:/db
      - node-ipc-preview:/ipc
    restart: on-failure

  cardano-db-sync-preview:
#    image: ghcr.io/intersectmbo/cardano-db-sync:13.2.0.2
    profiles: ["preview"]
    build:
      context: .
      target: cardano-db-sync
    env_file: ./.env
    command: [
      "--config", "config/cardano-db-sync/config.json",
      "--socket-path", "/node-ipc/node.socket",
      "--consumed-tx-out"
    ]
    environment:
      - EKG=Y
      - RESTORE_SNAPSHOT=${RESTORE_SNAPSHOT_PREVIEW:-}
      - POSTGRES_HOST=postgres-preview
      - POSTGRES_PORT=5432
    depends_on:
      - cardano-node-ogmios-preview
      - postgres-preview
    volumes:
      - ./config/cardano-configurations/network/preview:/config
      - node-ipc-preview:/node-ipc
      - db-sync-data-preview:/var/lib/cexplorer
    restart: on-failure
    stop_signal: SIGINT
    logging:
      driver: "local"
      options:
        max-size: "200k"
        max-file: "10"

  koios-tiny-preview:
    profiles: ["preview"]
    build:
      context: .
      target: koios-tiny
    env_file: ./.env
    environment:
      - NETWORK=preview
      - POSTGRES_HOST=postgres-preview
      - POSTGRES_PORT=5432
      - PGHOST=postgres-preview
      - PGPORT=5432
      - PGRST_DB_URI=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres-preview:5432/$POSTGRES_DB
    ports:
      - 127.0.0.1:8052:8050
    depends_on:
      - postgres-preview
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  db-sync-data-preview:
  node-db-preview:
  node-ipc-preview:
  postgres-data-preview:
